### ISSUE TITLE
Test Running Error

### ISSUE THREAD

**Issue by DarrenZhang01** [google/neural-tangents#40]
Hi, I reinstalled some packages and I reran the tests of Neural Tangents (latest version). But I am getting an interesting error and have not found a solution. Previously I ran Neural Tangents tests and this error never occurred. Has anyone else encountered this issue before and can give me some hints? Thanks!

```
ERROR: test_sample_vs_analytic_nngp_[batch_size=4, device_count=1 store_on_device=False ] (__main__.MonteCarloTest)
test_sample_vs_analytic_nngp_[batch_size=4, device_count=1 store_on_device=False ] (__main__.MonteCarloTest)
test_sample_vs_analytic_nngp_[batch_size=4, device_count=1 store_on_device=False ](batch_size=4, device_count=1, store_on_device=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1955, in shape
    result = a.shape
AttributeError: 'tuple' object has no attribute 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/absl/testing/parameterized.py", line 263, in bound_param_test
    test_method(self, **testcase_params)
  File "monte_carlo_test.py", line 152, in test_sample_vs_analytic_nngp
    ker_empirical = sample(x1, x2, 'nngp')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/utils.py", line 84, in h
    return g(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/utils.py", line 118, in getter_fn
    fn_out = fn(*canonicalized_args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/monte_carlo.py", line 103, in get_sampled_kernel
    for n, sample in get_samples(x1, x2, get, **apply_fn_kwargs):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/monte_carlo.py", line 77, in get_samples
    one_sample = kernel_fn_sample_once(x1, x2, split, get, **apply_fn_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/utils.py", line 84, in h
    return g(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 363, in serial_fn
    return serial_fn_x1(x1_or_kernel, x2, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 327, in serial_fn_x1
    _, kernel = _scan(row_fn, 0, x1s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 122, in _scan
    carry, y = f(carry, x)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 322, in row_fn
    return _, _scan(col_fn, x1, x2s)[1]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 122, in _scan
    carry, y = f(carry, x)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 325, in col_fn
    return x1, kernel_fn(x1, x2, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/utils.py", line 84, in h
    return g(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 294, in kernel_fn
    return device_put(_kernel_fn(x1, x2, *args, **kwargs), devices('cpu')[0])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/utils.py", line 84, in h
    return g(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 458, in parallel_fn
    return parallel_fn_x1(x1_or_kernel, x2, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 431, in parallel_fn_x1
    kernel = kernel_fn(x1, x2, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/utils.py", line 84, in h
    return g(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 593, in f_pmapped
    return _f(x_or_kernel, *args_np)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/api.py", line 169, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/core.py", line 1100, in call_bind
    outs = primitive.impl(fun, *args, **params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/xla.py", line 541, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/linear_util.py", line 221, in memoized_fun
    ans = call(fun, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/xla.py", line 607, in _xla_callable
    jaxpr, pvals, consts = pe.trace_to_jaxpr(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 429, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/api.py", line 869, in batched_fun
    out_flat = batching.batch(flat_fun, args_flat, in_axes_flat,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/batching.py", line 34, in batch
    return batched_fun.call_wrapped(*in_vals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/batch.py", line 586, in _f
    return f(_x_or_kernel, *_args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/neural_tangents/utils/monte_carlo.py", line 53, in kernel_fn_sample_once
    keys = np.where(utils.x1_is_x2(x1, x2), dropout_key1,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/numpy/lax_numpy.py", line 1283, in where
    return _where(condition, x, y)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/api.py", line 169, in f_jitted
    out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/core.py", line 1103, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/core.py", line 1112, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/batching.py", line 148, in process_call
    vals_out = call_primitive.bind(f, *vals, **params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/core.py", line 1103, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/core.py", line 1112, in process
    return trace.process_call(self, fun, tracers, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 186, in process_call
    jaxpr, out_pvals, consts, env_tracers = self.partial_eval(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 298, in partial_eval
    out_flat, (out_avals, jaxpr, env) = app(f, *in_consts), aux()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/core.py", line 1100, in call_bind
    outs = primitive.impl(fun, *args, **params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/xla.py", line 541, in _xla_call_impl
    compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/linear_util.py", line 221, in memoized_fun
    ans = call(fun, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/xla.py", line 607, in _xla_callable
    jaxpr, pvals, consts = pe.trace_to_jaxpr(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/interpreters/partial_eval.py", line 429, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/linear_util.py", line 150, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/numpy/lax_numpy.py", line 1267, in _where
    condition, x, y = broadcast_arrays(condition, x, y)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/numpy/lax_numpy.py", line 1328, in broadcast_arrays
    shapes = [shape(arg) for arg in args]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/numpy/lax_numpy.py", line 1328, in <listcomp>
    shapes = [shape(arg) for arg in args]
  File "<__array_function__ internals>", line 5, in shape
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 1957, in shape
    result = asarray(a).shape
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jax/core.py", line 450, in __array__
    raise Exception(msg)
Exception: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ShapedArray(uint32[2])>with<BatchTrace(level=0/2)>
  with val = Traced<ShapedArray(uint32[1,2]):JaxprTrace(level=-1/2)>
       batch_dim = 0.

This error can occur when a JAX Tracer object is passed to a raw numpy function, or a method on a numpy.ndarray object. You might want to check that you are using `jnp` together with `import jax.numpy as jnp` rather than using `np` via `import numpy as np`. If this error arises on a line that involves array indexing, like `x[idx]`, it may be that the array being indexed `x` is a raw numpy.ndarray while the indices `idx` are a JAX Tracer instance; in that case, you can instead write `jax.device_put(x)[idx]`.
```

**Comment by romanngg** [comment]
Thanks for reporting this - looks like JAX or our code specifically doesn't go along with numpy 1.19, could you try with
```
pip install numpy=1.18.5
```
?

Interestingly, our tests have been also failing but reported as passing... https://travis-ci.org/github/google/neural-tangents/jobs/704287384

**Comment by DarrenZhang01** [comment]
Thanks for the reply, Roman! If you look into the execution log of travis CI, those tests actually failed.

**Comment by DarrenZhang01** [comment]
But as you mentioned, Numpy version is indeed the problem. Take Monte Carlo tests for example, all of them failed with Numpy 1.19, but they work fine with 1.18.

**Comment by DarrenZhang01** [comment]
> Interestingly, our tests have been also failing but reported as passing... https://travis-ci.org/github/google/neural-tangents/jobs/704287384

Wrong exiting code (0) which misleads Travis CI might be the problem? [https://stackoverflow.com/questions/24972098/unit-test-script-returns-exit-code-0-even-if-tests-fail](https://stackoverflow.com/questions/24972098/unit-test-script-returns-exit-code-0-even-if-tests-fail)

**Comment by romanngg** [comment]
Thanks again for reporting this silent bug! It's now fixed with https://github.com/google/neural-tangents/commit/11d70e11c3ddcc11feae65f502ac0c42291b52ce (numpy 1.19 compatible), and https://github.com/google/neural-tangents/commit/148ba2b0adc3f9acf1da8e9135991bee1139a518 (makes the `for` shell loop exit with code 1 if it fails mid-loop; here's a sample of a failing test https://travis-ci.org/github/google/neural-tangents/builds/705595567/config and passing master: https://travis-ci.org/github/google/neural-tangents/builds/705590810).
